// `npm run gen:api`: backend/openapi.json -> src/shared/types/openapi.d.ts. Spec 002, FR-API-01.
// P7: `check:api` imports `generate` from here, so both produce the file the same way.
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { parseArgs } from 'node:util'

import openapiTS, { astToString } from 'openapi-typescript'

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** The schema the backend commits. Never a running server (FR-API-01). */
export const DEFAULT_SCHEMA_PATH = resolve(frontendRoot, '../backend/openapi.json')

/** The generated file, committed next to the code that uses it. */
export const TYPES_PATH = resolve(frontendRoot, 'src/shared/types/openapi.d.ts')

const HEADER = `/**
 * Generated by \`npm run gen:api\` from backend/openapi.json (spec 002, FR-API-01).
 * Do not edit this file by hand: change the backend, then regenerate.
 */

`

/**
 * Normalise line endings, so a Windows checkout and CI compare equal.
 * @param {string} text
 * @returns {string}
 */
export function normalise(text) {
  return text.replace(/\r\n?/g, '\n')
}

/**
 * Generate the TypeScript declarations for one OpenAPI schema file.
 * @param {string} [schemaPath] defaults to `../backend/openapi.json`
 * @returns {Promise<string>}
 */
export async function generate(schemaPath = DEFAULT_SCHEMA_PATH) {
  const source = await readFile(schemaPath, 'utf8')
  // Parsing here, rather than handing openapi-typescript a URL, keeps the result independent of
  // where the file lives and of the process cwd.
  /** @type {import('openapi-typescript').OpenAPI3} */
  const schema = JSON.parse(source)
  const ast = await openapiTS(schema, { silent: true })
  return normalise(HEADER + astToString(ast))
}

/**
 * The `--schema <path>` option shared by `gen:api` and `check:api`.
 * @param {string[]} argv
 * @returns {string}
 */
export function schemaPathFromArgs(argv) {
  const { values } = parseArgs({ args: argv, options: { schema: { type: 'string' } } })
  return values.schema === undefined ? DEFAULT_SCHEMA_PATH : resolve(values.schema)
}

/**
 * True when this module is the script node was started with, not an import.
 * @param {string} moduleUrl
 * @returns {boolean}
 */
export function isMain(moduleUrl) {
  const entry = process.argv[1]
  return entry !== undefined && pathToFileURL(resolve(entry)).href === moduleUrl
}

if (isMain(import.meta.url)) {
  const schemaPath = schemaPathFromArgs(process.argv.slice(2))
  const types = await generate(schemaPath)
  await mkdir(dirname(TYPES_PATH), { recursive: true })
  await writeFile(TYPES_PATH, types, 'utf8')
  console.log(`gen:api: wrote ${TYPES_PATH} from ${schemaPath}`)
}
